name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: { branches: [ main ] }
  # Run this workflow once per day, at 10:15 UTC
  schedule: [ { cron: "15 10 * * *" } ]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: { }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        name: Checkout openDAL repo
        with:
          repository: apache/opendal
          path: opendal
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Setup rust-script
        run: cargo install rust-script

      - run: yarn install
      - run: yarn run build
        env:
          REPO_PATH: ${{ github.workspace }}/opendal
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit to gitHub
        run: |
          git add dist
          git commit -m "Update docs" --author="github-actions[bot] <20685961+github-actions[bot]@users.noreply.github.com>"
          git push origin main
