name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: { branches: [ main ] }
  # Run this workflow once per day, at 10:15 UTC
  schedule: [ { cron: "15 10 * * *" } ]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: { }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Setup rust-script
        run: cargo install rust-script@0.35.0

      - name: Checkout openDAL repo
        run:
          git clone git@github.com:apache/opendal.git ~/opendal

      - run: yarn install
      - run: yarn run build
        env:
          REPO_PATH: ~/opendal
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit to gitHub
        run: |
          git config --global user.email "20685961+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist
          git commit -m "bot: update dist"
          git push origin main
